version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of the dependency files
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
      interval: "weekly"
    ignore:
      - dependency-name: "numpy"
